### PR TITLE
New (third party) SIDs added, SIDs Minimum size for brute force

### PR DESCRIPTION
**Pull request by Lexus89**
Fixed this first to test, others will follow

### CODE REVIEW

**Comment by Lexus89** [comment]
Added the --sids-min-size option again through this commit and changed some typo's/misspelling. I hope this works better now.

**Comment by quentinhardy** [comment]
Why do you want to delete some column names in Constants.py (ex: "%motdepasse%", %mot_de_passe%') ?

I'm ok with all other commits.

Thank you again for the help on this project.

**Comment by Lexus89** [comment]
The reason for that is due to the %% signs; when selecting info in a LIKE statement like %pass% it searches for a string that contains the string "pass" with/without info before/after it. This means the search for %pass% will also find %mot_de_PASSe% and %motdePASSe% etc.

Glad to help and thanks again for this amazing tool! My favorite for testing Oracle databases :) Hope it stays under development.

**Comment by quentinhardy** [comment]
You're right. Thank you.

I will try to stay under development on this project.
Don't hesitate to help me on this project.

**Pull request merged**
